### PR TITLE
Initial migration

### PR DESCRIPTION
**Pull request by fileman**

### CODE REVIEW

**Comment by ADefWebserver** [comment]
If this works do you plan to submit a pull request to the main project?

**Comment by fileman** [comment]
yes, but I dont know if for abosulteUri was the right way

**Comment by ADefWebserver** [comment]
> yes, but I dont know if for abosulteUri was the right way

@fileman I suggest submitting the PR and letting @sbwalker decide

**Comment by fileman** [comment]
> @fileman I suggest submitting the PR and letting @sbwalker decide

done

**Pull request closed without merging**
